name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 获取代码
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: npm安装
        run: npm install

      - name: 运行自动化脚本
        run: bash gen.js
          
      - name: blog编译
        run: npm run docs:build

      - name: 部署
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist
