name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 获取代码
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: 环境准备
        run: npm install

      - name: blog目录生成
        run: gen_blog_catalog.js
          
      - name: 构建
        run: npm run docs:build

      - name: 部署
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist
